from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_RIGHT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    KeepTogether
)
from datetime import datetime

DARK_BG = colors.HexColor("#0D1117")
ACCENT =  colors.HexColor("#58A6FF")
ACCENT2 = colors.HexColor("#3FB950")
DANGER = colors.HexColor("#F85149")
WARNING_COL = colors.HexColor("#D29922")
INFO_COL = colors.HexColor("#58A6FF")
SURFACE = colors.HexColor("#161B22")
BORDER = colors.HexColor("#30363D")
TEXT_PRIMARY = colors.HexColor("#E6EDF3")
TEXT_SECONDARY = colors.HexColor("#8B949E")
WHITE = colors.white

SEVERITY_COLORS = {
    "critical": DANGER,
    "warning": WARNING_COL,
    "info": INFO_COL,
    "high": DANGER,
    "medium": WARNING_COL,
    "low": ACCENT2,
}

def get_styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("title", fontName="Helvetica-Bold", fontSize=26,textColor=TEXT_PRIMARY, leading=32, spaceAfter=4
        ),
        "subtitle": ParagraphStyle("subtitle", fontName="Helvetica", fontSize=11,textColor=TEXT_SECONDARY, leading=16, spaceAfter=12
        ),
        "h1": ParagraphStyle("h1", fontName="Helvetica-Bold", fontSize=15,textColor=ACCENT, leading=20, spaceBefore=18, spaceAfter=8,borderPad=0
        ),
        "h2": ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=12,textColor=TEXT_PRIMARY, leading=16, spaceBefore=10, spaceAfter=4
        ),
        "body": ParagraphStyle("body", fontName="Helvetica", fontSize=9,textColor=TEXT_SECONDARY, leading=14, spaceAfter=4
        ),
        "body_white": ParagraphStyle("body_white", fontName="Helvetica", fontSize=9,textColor=TEXT_PRIMARY, leading=14, spaceAfter=4
        ),
        "mono": ParagraphStyle("mono", fontName="Courier", fontSize=8,textColor=ACCENT2, leading=12, spaceAfter=2
        ),
        "label": ParagraphStyle("label", fontName="Helvetica-Bold", fontSize=8,textColor=TEXT_SECONDARY, leading=10, spaceAfter=2
        ),
        "tag": ParagraphStyle("tag", fontName="Helvetica-Bold", fontSize=7,textColor=WHITE, leading=10
        ),
        "positive": ParagraphStyle("positive", fontName="Helvetica", fontSize=9,textColor=ACCENT2, leading=14, spaceAfter=3,leftIndent=12
        ),
        "summary": ParagraphStyle("summary", fontName="Helvetica", fontSize=10,textColor=TEXT_PRIMARY, leading=16, spaceAfter=8,borderPad=8
        ),
    }
    
class PageCanvas:
    """Custom canvas for headers and footers."""
    def __init__(self, filename, **kwargs):
        self.filename = filename
        self.saved_page_states = []
        
    def afterFlowable(self, flowable):
        pass
    
class PageCanvas:
    """Custom canvas for headers/footers."""
    def __init__(self, filename, **kwargs):
        self.filename = filename
        self.saved_page_states = []
 
    def afterFlowable(self, flowable):
        pass
 
 
def draw_page_decorations(canvas_obj, doc):
    canvas_obj.saveState()
    w, h = A4
 
    # Top bar
    canvas_obj.setFillColor(SURFACE)
    canvas_obj.rect(0, h - 40, w, 40, fill=1, stroke=0)
 
    # Accent line
    canvas_obj.setFillColor(ACCENT)
    canvas_obj.rect(0, h - 42, w, 2, fill=1, stroke=0)
 
    # Header text
    canvas_obj.setFont("Helvetica-Bold", 9)
    canvas_obj.setFillColor(TEXT_PRIMARY)
    canvas_obj.drawString(2*cm, h - 26, "AI CODE REVIEW REPORT")
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.setFillColor(TEXT_SECONDARY)
    canvas_obj.drawRightString(w - 2*cm, h - 26, datetime.now().strftime("%Y-%m-%d"))
 
    # Footer
    canvas_obj.setFillColor(SURFACE)
    canvas_obj.rect(0, 0, w, 28, fill=1, stroke=0)
    canvas_obj.setFillColor(BORDER)
    canvas_obj.rect(0, 28, w, 1, fill=1, stroke=0)
    canvas_obj.setFont("Helvetica", 7)
    canvas_obj.setFillColor(TEXT_SECONDARY)
    canvas_obj.drawString(2*cm, 10, "Generated by AI Code Review Assistant")
    canvas_obj.drawRightString(w - 2*cm, 10, f"Page {doc.page}")
 
    canvas_obj.restoreState()
 
 
def score_bar_table(label: str, score: int, color=ACCENT):
    """Render a labeled progress bar as a table row."""
    bar_width = 120
    filled = int(bar_width * score / 100)
 
    bar_data = [[
        Paragraph(label, ParagraphStyle("sl", fontName="Helvetica", fontSize=8,
                                        textColor=TEXT_SECONDARY, leading=10)),
        Paragraph(f"{score}/100", ParagraphStyle("sv", fontName="Helvetica-Bold",
                                                  fontSize=8, textColor=TEXT_PRIMARY, leading=10))
    ]]
    t = Table(bar_data, colWidths=[100, 50])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t
 
 
def severity_badge(severity: str) -> Table:
    col = SEVERITY_COLORS.get(severity.lower(), INFO_COL)
    styles = get_styles()
    data = [[Paragraph(severity.upper(), styles["tag"])]]
    t = Table(data, colWidths=[50])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), col),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))
    return t
 
 
def issue_block(item: dict, category: str, styles: dict) -> list:
    """Render a single issue as a styled block."""
    elements = []
    severity = item.get("severity") or item.get("priority", "info")
    col = SEVERITY_COLORS.get(severity.lower(), INFO_COL)
 
    title = item.get("title", "Untitled")
    file_name = item.get("file", "")
    desc = item.get("description", "")
    fix = item.get("fix") or item.get("benefit", "")
    cwe = item.get("cwe", "")
    line = item.get("line_hint", "")
 
    # Header row: badge + title + file
    header_parts = [severity_badge(severity)]
    title_text = f"<b>{title}</b>"
    if file_name and file_name != "General":
        title_text += f'  <font color="#8B949E" size="7">  {file_name}'
        if line:
            title_text += f" : {line}"
        title_text += "</font>"
    if cwe:
        title_text += f'  <font color="#D29922" size="7">  {cwe}</font>'
 
    header_parts.append(Paragraph(title_text, ParagraphStyle(
        "it", fontName="Helvetica-Bold", fontSize=9,
        textColor=TEXT_PRIMARY, leading=14
    )))
 
    header_table = Table([header_parts], colWidths=[60, 390])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
 
    # Full block with left accent bar
    block_rows = [[header_table]]
    if desc:
        block_rows.append([Paragraph(desc, styles["body"])])
    if fix:
        block_rows.append([Paragraph(f"<b>Fix:</b> {fix}", ParagraphStyle(
            "fix", fontName="Helvetica", fontSize=8,
            textColor=ACCENT2, leading=12
        ))])
 
    inner = Table(block_rows, colWidths=[450])
    inner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))
 
    outer = Table([[
        Table([[""]], colWidths=[4], rowHeights=[None]),
        inner
    ]], colWidths=[6, 452])
    outer.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), col),
        ("BACKGROUND", (1, 0), (1, -1), SURFACE),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("LINEBELOW", (0, 0), (-1, -1), 1, BORDER),
    ]))
 
    elements.append(KeepTogether([outer, Spacer(1, 6)]))
    return elements
 
 
def generate_pdf_report(analysis: dict, output_path: str):
    styles = get_styles()
    w, h = A4
    margin = 2 * cm
 
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=margin, rightMargin=margin,
        topMargin=margin + 30, bottomMargin=margin + 10,
    )
 
    story = []
 
    # Cover / Header 
    repo_url = analysis.get("repo_url", "Uploaded Code")
    grade = analysis.get("grade", "B")
    overall = analysis.get("overall_score", 75)
    summary = analysis.get("summary", "")
    tech_stack = analysis.get("tech_stack", [])
    stats = analysis.get("stats", {})
 
    story.append(Spacer(1, 10))
 
    # Title block
    title_data = [[
        Paragraph("CODE REVIEW", ParagraphStyle(
            "big", fontName="Helvetica-Bold", fontSize=28,
            textColor=TEXT_PRIMARY, leading=32
        )),
        Paragraph(grade, ParagraphStyle(
            "grade", fontName="Helvetica-Bold", fontSize=48,
            textColor=ACCENT, leading=52, alignment=TA_RIGHT
        )),
    ]]
    title_table = Table(title_data, colWidths=[360, 100])
    title_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
        ("TOPPADDING", (0, 0), (-1, -1), 16),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 16),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("LINEBELOW", (0, 0), (-1, -1), 2, ACCENT),
    ]))
    story.append(title_table)
    story.append(Spacer(1, 8))
 
    story.append(Paragraph(repo_url, ParagraphStyle(
        "repo", fontName="Courier", fontSize=9,
        textColor=ACCENT2, leading=12
    )))
    story.append(Paragraph(
        datetime.now().strftime("Analyzed %B %d, %Y at %H:%M"),
        styles["label"]
    ))
    story.append(Spacer(1, 12))
 
    # Stats row
    stat_items = [
        ("Files", str(stats.get("files_analyzed", len(analysis.get("files_reviewed", []))))),
        ("Issues", str(stats.get("total_issues", 0))),
        ("Critical", str(stats.get("critical_count", 0))),
        ("Warnings", str(stats.get("warning_count", 0))),
        ("Score", f"{overall}/100"),
    ]
    stat_cells = []
    for label, val in stat_items:
        cell = Table([[
            Paragraph(val, ParagraphStyle("sv2", fontName="Helvetica-Bold",
                                           fontSize=20, textColor=ACCENT, leading=24, alignment=TA_CENTER)),
        ], [
            Paragraph(label, ParagraphStyle("sl2", fontName="Helvetica",
                                             fontSize=7, textColor=TEXT_SECONDARY, leading=10, alignment=TA_CENTER)),
        ]], colWidths=[87])
        cell.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 1, BORDER),
        ]))
        stat_cells.append(cell)
 
    stats_row = Table([stat_cells], colWidths=[91] * 5)
    stats_row.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("LINEBELOW", (0, 0), (-1, -1), 2, ACCENT),
    ]))
    story.append(stats_row)
    story.append(Spacer(1, 14))
 
    # Summary
    if summary:
        story.append(Paragraph("OVERVIEW", styles["h1"]))
        story.append(Paragraph(summary, styles["summary"]))
 
    # Score bars
    scores = [
        ("Overall Quality", overall, ACCENT),
        ("Maintainability", analysis.get("maintainability_score", 70), ACCENT2),
        ("Security", analysis.get("security_score", 70), WARNING_COL),
        ("Performance", analysis.get("performance_score", 70), INFO_COL),
    ]
    score_rows = []
    for label, val, col in scores:
        score_rows.append([
            Paragraph(label, ParagraphStyle("sl3", fontName="Helvetica", fontSize=8,
                                             textColor=TEXT_SECONDARY, leading=12)),
            Paragraph(f"{val}", ParagraphStyle("sv3", fontName="Helvetica-Bold", fontSize=8,
                                                textColor=col, leading=12, alignment=TA_RIGHT)),
        ])
    scores_table = Table(score_rows, colWidths=[350, 110])
    scores_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("LINEBELOW", (0, 0), (-1, -2), 1, BORDER),
        ("LINEBELOW", (0, -1), (-1, -1), 2, ACCENT),
    ]))
    story.append(scores_table)
    story.append(Spacer(1, 6))
 
    # Tech stack
    if tech_stack:
        story.append(Spacer(1, 6))
        tech_cells = []
        for tech in tech_stack[:12]:
            c = Table([[Paragraph(tech, ParagraphStyle(
                "tech", fontName="Helvetica-Bold", fontSize=7,
                textColor=ACCENT, leading=10
            ))]])
            c.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("BOX", (0, 0), (-1, -1), 1, ACCENT),
            ]))
            tech_cells.append(c)
 
        # Wrap into rows of 6
        for i in range(0, len(tech_cells), 6):
            row = tech_cells[i:i+6]
            while len(row) < 6:
                row.append(Paragraph("", styles["body"]))
            t = Table([row], colWidths=[75] * 6)
            t.setStyle(TableStyle([
                ("LEFTPADDING", (0, 0), (-1, -1), 2),
                ("RIGHTPADDING", (0, 0), (-1, -1), 2),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]))
            story.append(t)
        story.append(Spacer(1, 8))
 
    # Sections 
    sections = [
        ("BUG RISKS", analysis.get("bug_risks", []), "bug"),
        ("SECURITY CONCERNS", analysis.get("security_concerns", []), "security"),
        ("COMPLEXITY WARNINGS", analysis.get("complexity_warnings", []), "complexity"),
        ("REFACTORING SUGGESTIONS", analysis.get("refactoring_suggestions", []), "refactor"),
    ]
 
    for section_title, items, category in sections:
        if not items:
            continue
        story.append(Paragraph(section_title, styles["h1"]))
        for item in items:
            story.extend(issue_block(item, category, styles))
        story.append(Spacer(1, 8))
 
    # Positives
    positives = analysis.get("positive_highlights", [])
    if positives:
        story.append(Paragraph("WHAT'S WORKING WELL", styles["h1"]))
        for p in positives:
            story.append(Paragraph(f"✓  {p}", styles["positive"]))
        story.append(Spacer(1, 8))
 
    # Test Coverage Note
    test_note = analysis.get("test_coverage_note", "")
    if test_note:
        story.append(Paragraph("TESTING", styles["h1"]))
        story.append(Paragraph(test_note, styles["body_white"]))
        story.append(Spacer(1, 8))
 
    # Files Reviewed
    files_reviewed = analysis.get("files_reviewed", [])
    if files_reviewed:
        story.append(Paragraph("FILES ANALYZED", styles["h1"]))
        file_rows = [[Paragraph(f, ParagraphStyle(
            "fr", fontName="Courier", fontSize=7,
            textColor=ACCENT2, leading=10
        ))] for f in files_reviewed[:50]]
        ft = Table(file_rows, colWidths=[460])
        ft.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("LINEBELOW", (0, 0), (-1, -2), 1, BORDER),
        ]))
        story.append(ft)
 
    doc.build(story, onFirstPage=draw_page_decorations, onLaterPages=draw_page_decorations)